FROM golang:1.21-alpine AS validator

RUN go install github.com/hiAndrewQuinn/cliguard@latest

WORKDIR /app
COPY . .

ENTRYPOINT ["cliguard", "validate", "--project-path", ".", "--entrypoint", "cmd.NewRootCmd"]